### PR TITLE
alarm stops

### PR DESCRIPTION
**Pull request by SarahNox**
alarm stops
shows alert
changes pause/resume button to start

### CODE REVIEW

**Comment by sharnik** [comment]
Is it accepted by Daniel and ready to merge?

**Comment by SarahNox** [comment]
yes, accepted and ready

**Comment by sharnik** [comment]
Cool!

**Comment by SarahNox** [comment]
Hey,

I have a question: 
the "activate from pause“ issue is solved, but do I have to create a new branch for „pausing during the pomodoro-time“? 
as it got already solved during the „activate from pause“issue.

cu
Sarah

**Comment by sharnik** [comment]
No, if Daniel accepts it, just close the issue.

**Comment by SarahNox** [comment]
I'll show it Daniel this evening. 

Von meinem iPhone gesendet

**Pull request merged**
